name: Composer Edition

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Composer Search and Replace name
        uses: jossef/action-set-json-field@v1
        with:
          file: composer.json
          field: name
          value: php-prefixer/prefixed-illuminate-support
      - name: Composer Search and Replace description
        uses: jossef/action-set-json-field@v1
        with:
          file: composer.json
          field: description
          value: The Prefixed Illuminate Support package.
      - name: Composer Search and Replace description
        uses: jossef/action-set-json-field@v1
        with:
          file: composer.json
          field: homepage
          value: https://php-prefixer.com
      - name: Composer Search and Replace authors.name
        uses: jossef/action-set-json-field@v1
        with:
          file: composer.json
          field: authors.name
          value: Anibal Sanchez
      - name: Composer Search and Replace authors.email
        uses: jossef/action-set-json-field@v1
        with:
          file: composer.json
          field: authors.email
          value: anibal.sanchez@php-prefixer.com