name: Prefixer

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout PHP-Prefixer/prefixed-illuminate-support'
        uses: actions/checkout@v2

      - name: 'Checkout illuminate/support'
        uses: actions/checkout@v2
        with:
          name: illuminate/support     # clones https://github.com/illuminate/support
          ref: refs/heads/6.x
          path: illuminate/support

      - name: 'Check'
        run: |
          ls -alhR
#
#      - name: Run PHP-Prefixer
#        uses: PHP-Prefixer/php-prefixer-build-action@v0.0.6
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          project_id: ${{ secrets.PROJECT_ID }}