name: PHP-Prefixer for 6.x

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 10 * * 6'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Run PHP-Prefixer
        uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repository: 'illuminate/support'
          ref: '6.x'
          schema: >
            {"project-name": "Prefixed Project","namespaces-prefix": "PPP","global-scope-prefix": "PPP_"}

