on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout PHP-Prefixer/prefixed-illuminate-support'
        uses: actions/checkout@v2

      - name: 'Checkout illuminate/support'
        uses: actions/checkout@v2
        with:
          repository: 'illuminate/support'
          ref: refs/heads/7.x
          path: illuminate/support

            #     - name: 'Configure PHP-Prefixer composer.json - project-name'
            #        uses: jossef/action-set-json-field@v1
            #        with:
            #          file: composer.json
            #          field: extra.php-prefixer.project-name
            #          value: Prefixed Illuminate Support
            #
            #      - name: 'Configure PHP-Prefixer composer.json - namespaces-prefix'
            #        uses: jossef/action-set-json-field@v1
            #        with:
            #          file: composer.json
            #          field: extra.php-prefixer.namespaces-prefix
            #          value: PPP
            #
            #      - name: 'Configure PHP-Prefixer composer.json - global-scope-prefix'
            #        uses: jossef/action-set-json-field@v1
            #        with:
            #          file: composer.json
            #          field: extra.php-prefixer.global-scope-prefix
            #          value: PPP_

      - name: Run PHP-Prefixer
        uses: jackstr/php-prefixer-build-action@dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          source_dir_path: illuminate/support
          target_branch: 7.x-prefixed
          gh_personal_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
