name: PHP-Prefixer for 8.x

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 10 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # PHP-Prefixer Execution Job
      - name: Run PHP-Prefixer
        uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repository: 'illuminate/support'
          ref: '8.x'
          schema: >
            {"project-name": "Prefixed Illuminate package","namespaces-prefix": "PPP_L8","global-scope-prefix": "PPP_L8_"}

      # composer.json Edition
      - uses: actions/checkout@v2
        with:
          ref: 'prefixed-8.x'
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Improve composer.json fields
        run: |
          sed -i 's/illuminate\/support/php-prefixer\/prefixed-illuminate-support/' '${{ github.workspace }}/composer.json'
          sed -i 's/The Illuminate Support package./The Prefixed Illuminate Support package./' '${{ github.workspace }}/composer.json'
          sed -i 's/laravel\.com/php-prefixer\.com/' '${{ github.workspace }}/composer.json'
          sed -i 's/laravel\/framework/PHP-Prefixer\/prefixed-illuminate-support/' '${{ github.workspace }}/composer.json'
          sed -i 's/Taylor Otwell/Anibal Sanchez/' '${{ github.workspace }}/composer.json'
          sed -i 's/laravel\.com/php-prefixer.com/' '${{ github.workspace }}/composer.json'
          sed -i 's/taylor/anibal.sanchez/' '${{ github.workspace }}/composer.json'
          sed -i 's/branch-alias/php-prefixer/' '${{ github.workspace }}/composer.json'
          sed -i 's/dev-master/last-build/' '${{ github.workspace }}/composer.json'
          sed -i "s/[0-9].x-dev/`date`/" '${{ github.workspace }}/composer.json'
      - name: Configure git
        run: |
          git config --local user.email "team@php-prefixer.com"
          git config --local user.name "PHP-Prefixer DevOps"
          export CHANGED=$(git status --porcelain)
      - name: Commit files
        if: ${{ contains(env.CHANGED, 'M ') }}
        run: |
          git add -A
          git commit -m "Update composer.json info."
          git push