on:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 8 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout PHP-Prefixer/prefixed-illuminate-support'
        uses: actions/checkout@v2

      - name: 'Checkout illuminate/support'
        uses: actions/checkout@v2
        with:
          repository: 'illuminate/support'
          ref: refs/heads/8.x
          path: illuminate/support

      - name: Run PHP-Prefixer
        uses: jackstr/php-prefixer-build-action@dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          source_dir_path: illuminate/support
          target_branch: 8.x-prefixed
          gh_personal_access_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
