name: PHP-Prefixer for 6.x

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 10 * * 6'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # PHP-Prefixer Execution Job
      - name: Run PHP-Prefixer
        uses: PHP-Prefixer/php-prefixer-build-action@v1.1.0
        with:
          personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          repository: 'illuminate/support'
          ref: '6.x'
          schema: >
            {"project-name": "Prefixed Project","namespaces-prefix": "PPP","global-scope-prefix": "PPP_"}

      # composer.json Edition
      - uses: actions/checkout@v2
        with:
          ref: 'prefixed-6.x'
          fetch-depth: 0
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Composer Search and Replace name
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: name
          value: php-prefixer/prefixed-illuminate-support
      - name: Composer Search and Replace description
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: description
          value: The Prefixed Illuminate Support package.
      - name: Composer Search and Replace description
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: homepage
          value: https://php-prefixer.com
      - name: Composer Search and Replace authors.name
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: authors[0].name
          value: Anibal Sanchez
      - name: Composer Search and Replace authors.email
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: authors[0].email
          value: anibal.sanchez@php-prefixer.com
      - name: Composer Search and Replace support.issues
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: support.issues
          value: https://github.com/PHP-Prefixer/prefixed-illuminate-support/issues
      - name: Composer Search and Replace support.source
        uses: deef0000dragon1/json-edit-action/@v1
        with:
          file: composer.json
          field: support.source
          value: https://github.com/PHP-Prefixer/prefixed-illuminate-support

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update composer.json info."
          git push